### PR TITLE
redis-operator adapted for the sidecars

### PR DESCRIPTION
**Pull request by jaroslav-viravec**
-  [GH issue Redis backup](https://github.tools.sap/cs-devops/cs-devops/issues/16) 
- `sidecars[]` and `extraVolumes[]` added to the redis-operator
- new CRDS added

### CODE REVIEW

**Review by dafe-corporate-sap — APPROVED** [review]
LGTM

**Review by dafe-corporate-sap — APPROVED** [review]
LGTM

**Review by cbarbian-sap — COMMENTED** [review]
Few comments:
- please rename the import alias `apiv1` to `corev1` (which is common standard)
- the extra `if` statements in parameters.yaml (e.g. line 76, 82) are not needed (the `with` statement covers that)
- I'm not sure if I like putting `extraVolumes` under `persistence` (or if it should rather be at the root level); let me think about this a bit ...

**Comment by jaroslav-viravec** [comment]
> Few comments:
> 
> * please rename the import alias `apiv1` to `corev1` (which is common standard)
> * the extra `if` statements in parameters.yaml (e.g. line 76, 82) are not needed (the `with` statement covers that)
> * I'm not sure if I like putting `extraVolumes` under `persistence` (or if it should rather be at the root level); let me think about this a bit ...

Hello @cbarbian-sap,
the changes are committed, if you will have time please check the changes.
Thank you so much.

**Review by dafe-corporate-sap — APPROVED** [review]
LGTM

**Review by cbarbian-sap — APPROVED** [review]

**Pull request merged**
